#ifndef SCENE_SERIALIZER_HPP
#define SCENE_SERIALIZER_HPP

#include "scene.hpp"
#include <fstream>
#include <iomanip>
#include <sstream>

// Minimal JSON-like scene format serializer
// Format: Human-readable text format for scene data

class SceneSerializer {
public:
  static bool SaveToFile(const Scene &scene, const std::string &filepath) {
    std::ofstream file(filepath);
    if (!file.is_open()) {
      std::cerr << "[SceneSerializer] Failed to open file for writing: "
                << filepath << std::endl;
      return false;
    }

    file << "# Scene File Format v1.0\n";
    file << "# Auto-generated by OpenGL Engine\n\n";

    file << "scene {\n";

    const auto &entities = scene.GetEntities();
    for (const auto &entity : entities) {
      WriteEntity(file, *entity, 1);
    }

    file << "}\n";

    std::cout << "[SceneSerializer] Saved scene with " << entities.size()
              << " entities to: " << filepath << std::endl;
    return true;
  }

  static bool LoadFromFile(Scene &scene, const std::string &filepath) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
      std::cerr << "[SceneSerializer] Failed to open file for reading: "
                << filepath << std::endl;
      return false;
    }

    scene.Clear();

    std::string line;
    std::string currentEntityName;
    Transform currentTransform;
    bool inEntity = false;
    bool inTransform = false;

    while (std::getline(file, line)) {
      line = Trim(line);

      // Skip comments and empty lines
      if (line.empty() || line[0] == '#')
        continue;

      if (line.find("entity") == 0 && line.find("{") != std::string::npos) {
        // Extract entity name from: entity "name" {
        size_t start = line.find('"');
        size_t end = line.rfind('"');
        if (start != std::string::npos && end != std::string::npos &&
            end > start) {
          currentEntityName = line.substr(start + 1, end - start - 1);
        } else {
          currentEntityName = "Entity";
        }
        currentTransform = Transform();
        inEntity = true;
        inTransform = false;
      } else if (inEntity && line == "transform {") {
        inTransform = true;
      } else if (inTransform && line == "}") {
        inTransform = false;
      } else if (inEntity && !inTransform && line == "}") {
        // End of entity, create it
        auto entity = scene.CreateEntity(currentEntityName);
        entity->transform = currentTransform;
        inEntity = false;
      } else if (inTransform) {
        ParseTransformLine(line, currentTransform);
      }
    }

    std::cout << "[SceneSerializer] Loaded scene with "
              << scene.GetEntityCount() << " entities from: " << filepath
              << std::endl;
    return true;
  }

private:
  static void WriteEntity(std::ostream &out, const Entity &entity, int indent) {
    std::string tab(indent * 2, ' ');

    out << tab << "entity \"" << entity.GetName() << "\" {\n";

    WriteTransform(out, entity.transform, indent + 1);

    out << tab << "}\n";
  }

  static void WriteTransform(std::ostream &out, const Transform &t,
                             int indent) {
    std::string tab(indent * 2, ' ');

    out << tab << "transform {\n";
    out << tab << "  position " << t.Position.x << " " << t.Position.y << " "
        << t.Position.z << "\n";
    out << tab << "  rotation " << t.Rotation.x << " " << t.Rotation.y << " "
        << t.Rotation.z << "\n";
    out << tab << "  scale " << t.Scale.x << " " << t.Scale.y << " "
        << t.Scale.z << "\n";
    out << tab << "}\n";
  }

  static void ParseTransformLine(const std::string &line, Transform &t) {
    std::istringstream iss(line);
    std::string key;
    iss >> key;

    if (key == "position") {
      iss >> t.Position.x >> t.Position.y >> t.Position.z;
    } else if (key == "rotation") {
      iss >> t.Rotation.x >> t.Rotation.y >> t.Rotation.z;
    } else if (key == "scale") {
      iss >> t.Scale.x >> t.Scale.y >> t.Scale.z;
    }
  }

  static std::string Trim(const std::string &str) {
    size_t first = str.find_first_not_of(" \t\r\n");
    if (first == std::string::npos)
      return "";
    size_t last = str.find_last_not_of(" \t\r\n");
    return str.substr(first, last - first + 1);
  }
};

#endif // SCENE_SERIALIZER_HPP
