load("@com_google_impress//build_tools:imp.bzl",  "if_desktop", "imp_default_jni_linkopts", "imp_google3_copts", "if_android")
load("@com_google_impress//build_tools:assets.bzl", "imp_assets")
load("@com_google_impress//build_tools:imp_material.bzl", "imp_material")

package(
    default_applicable_licenses = [],
    default_visibility = [
        "//visibility:public",
    ],
    features = [
        "-use_header_modules",  # Incompatible with -std=c++14.
    ],
)

imp_material(
    name = "surface_material",
    src = ":surface_material.mat",
)

imp_assets(
    name = "surface_assets",
    srcs = [
        ":surface_material",
    ],
    namespace = "ix::samsung::homecomponents::data"
)

cc_library(
    name = "surface",
    srcs = [
        "surface_base.cc",
    ],
    hdrs = [
        "surface_base.h",
    ],
    copts = imp_google3_copts(),
    deps = [
        "@com_google_impress//:api",
        "@com_google_impress//core/geometry:geometry",
        ":surface_assets",
        "//native/components/tag:tag",
        "//native/components/bounding_box:bounding_box",
        "//native/data:home_components_assets",
        "//native:home_components_data",
        "//native/home_components_utils/common:HomeComponentsUtils",
        "//proto/components:interaction_state_proto_cc",
        "//samples/building_home/components/animated_piece:animated_piece",
    ],
)
